### PR TITLE
Provide a fallback to --Grid-gutter-size var.

### PR DESCRIPTION
**Pull request by dleitee**
Hi.
What do you think about adding a fallback to --Grid-gutter-size?
Thanks.

### CODE REVIEW

**Comment by simonsmith** [comment]
Hey @dleitee,

Have you ran into a scenario where you need this? Right now it will be `20px` unless overridden which works the same way.

**Comment by dleitee** [comment]
I am using post-css-variables, but it can not change the value of the variable, it remains 20px.

**Comment by dleitee** [comment]
I use: 
```css
:root {
  --Grid-gutter-size: 25px;
}

.grid {
  composes: Grid Grid--withGutter from 'suitcss-components-grid/lib/grid.css';
  width: 100%;
}

```

**Comment by simonsmith** [comment]
Does it work as expected with CSS modules? Just curious where the problem lies

**Comment by dleitee** [comment]
Yes, it worked, until I added the post-css-variables. 😞

**Comment by simonsmith** [comment]
Can you try https://github.com/postcss/postcss-custom-properties?

**Comment by dleitee** [comment]
Hey @simonsmith, I tried use: 
```css
@import "suitcss-components-grid";
:root {
  --Grid-gutter-size: 25px;
}
```
and my project is working correctly.

But, I have a question. Is there any problem in add this code?

`--Grid-gutter-size: var(--Grid-gutter-size, 20px);`

I think that will help a lot people.

**Comment by simonsmith** [comment]
> But, I have a question. Is there any problem in add this code?

It seems a bit redundant to assign the same value back to itself. Having you stopped using CSS modules now?

I'm asking because it would be interesting to find out if you experienced a bug in the postcss plugin or whether there something that needs to be altered in the SUIT components.

I was curious to know if just switching out the custom properties plugin in your original setup changed anything?

**Comment by dleitee** [comment]
> It seems a bit redundant to assign the same value back to itself. Having you stopped using CSS modules now?

In this case, you do not assign the same value back to itself, you will verify if `--Grid-gutter-size` have some value, if not, will assign the default value `20px`.

I'm using CSS modules yet, but without `composes`.

> I was curious to know if just switching out the custom properties plugin in your original setup changed anything?

I tested with both plugins, and both return the same thing.

**Pull request closed without merging**
