### PR TITLE
Use suit-preprocessor

### PR DESCRIPTION
**Pull request by simonsmith**
Pretty simple change, but mainly wanted to raise the idea of using `postcss-bem-linter` as part of `npm test`. This would then be added to each package.

A further step might be to add stylelint here to ensure all SUIT packages conform to the style guide.

### CODE REVIEW

**Comment by simonsmith** [comment]
Added the stylelint-config-suitcss. Works quite nicely as an additional test.

cc @giuseppeg @timkelty @jeddy3

**Comment by giuseppeg** [comment]
@simonsmith sorry I didn't see this. Do you mean use `postcss-bem-linter` as part of `npm test` but keep it in `suitcss-preprocessor` ? If so yeah sounds good to me.

**Comment by jeddy3** [comment]
@simonsmith Likewise, I just saw this now after getting back from my hols.

It's looking good to me btw.

> Do you mean use postcss-bem-linter as part of npm test but keep it in suitcss-preprocessor ? If so yeah sounds good to me.

Am I right in thinking that with [these changes](https://github.com/suitcss/preprocessor/commit/a2218c3604a6b4d78297f9247f48a1512a4d49f9) to `suitcss-preprocessor` you'll no longer use the `stylelint` plugin directly in this repo, but rather run both `postcss-bem-linter` and `stylelint` via `suitcss-preprocessor`? If so, looking super nice :)

**Comment by simonsmith** [comment]
Ha yeah, exactly. I realised adding stylelint manually to every package was going to be a waste of time. Once a new `preprocessor` version goes out it should work nicely.

**Pull request merged**
