### PR TITLE
Add flexbox modifier

### PR DESCRIPTION
**Pull request by timkelty**
Just thought I'd share what I've been using to get equal-height grid items with flexbox.

### CODE REVIEW

**Comment by AntonTrollback** [comment]
We have been using the following.. :)
This is definitely the missing feature in the suit grid.
Too bad flexbox seem to be the only way of solving it.

```
/**
 * Equal-height cells
 */

.Grid--equalHeight {
  display: flex;
  flex-wrap: wrap;
}

.Grid--equalHeight > .Grid-cell {
  display: flex;
}
```

**Comment by timkelty** [comment]
@AntonTrollback Nice!
Luckily flexbox support is getting pretty decent, and usually non-equal height grids aren't the end of the world for users in an older brower.

In the past we have used this in tandem with a modernizr test, and then conditionally applied an equal height JS solution. More and more we just let it go, though.

In actuality, I also had been prefixing those classes with a modernizr class just to make sure it doesn't mess with anything if there is no support.

**Comment by AntonTrollback** [comment]
Great changes!

Oh, I tested pretty much the same thing some time ago: 
https://github.com/AntonTrollback/grid/blob/master/grid.css
(`.flex` class is just a helper under development)

The interesting and annoying part is the [flex sizes](https://github.com/AntonTrollback/grid/blob/master/grid.css#L149).
Not sure they are needed, but I ended up adding it to fix this [messy grid](https://www.coop.se/handla-hemma-beta/varor/dryck/kaffe) in various browsers.

**Comment by AntonTrollback** [comment]
Note: columns doesn't not work as intended in firefox before version 29.

**Comment by oleersoy** [comment]
:+1: Nice work!

**Pull request closed without merging**
